name: Notify Host Repository

on:
  push:
    branches:
      - main  # Trigger when master is updated

jobs:
  notify-host:
    runs-on: ubuntu-latest

    steps:
      - name: Send Webhook to Host Repository
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.HOST_REPO_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/jurijambros/host/dispatches \
               -d '{"event_type": "shared-updated"}'
